CREATE SCHEMA IF NOT EXISTS ITEMS;

CREATE TABLE ITEMS.ITEMS (
  ITEM_ID SERIAL PRIMARY KEY,
  NAME CHAR(50) NOT NULL,
  DESCRIPTION TEXT,
  IMAGE_URL TEXT,
  MIN_BID_PRICE REAL NOT NULL,
  --DATE_TIME TIMESTAMP NOT NULL,
  USERNAME TEXT NOT NULL,
  STATUS SMALLINT NOT NULL, -- 1: AUCTIONED, 2: POSTED
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);