const ActionTypes = {
  // Auth
  SET_AUTHENTICATION: 'SET_AUTHENTICATION',
  // User
  FETCH_LOGIN_DETAILS_REQUESTED: 'FETCH_LOGIN_DETAILS_REQUESTED',
  FETCH_LOGIN_DETAILS_SUCCEEDED: 'FETCH_LOGIN_DETAILS_SUCCEEDED',
  FETCH_LOGIN_DETAILS_FAILURE: 'FETCH_LOGIN_DETAILS_FAILURE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_USER_PROFILE_SUCCEEDED: 'UPDATE_USER_PROFILE_SUCCEEDED',
  SET_USER_ROLE: 'SET_USER_ROLE',
  USER_LOGOUT: 'USER_LOGOUT',

  // Items
  ITEMS_DIALOG_OPEN: 'ITEMS_DIALOG_OPEN',
  ITEMS_DIALOG_CLOSE: 'ITEMS_DIALOG_CLOSE',
  FETCH_ALL_ITEMS_SUCCEEDED: 'FETCH_ALL_ITEMS_SUCCEEDED',
  FETCH_ALL_ITEMS_FAILURE: 'FETCH_ALL_ITEMS_FAILURE',
  SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',

  // Auctions
  FETCH_SLOTS_SUCCEEDED: 'FETCH_ALL_SLOTS_SUCCEEDED',
  FETCH_SLOTS_FAILURE: 'FETCH_ALL_SLOTS_FAILURE',
  FETCH_AUCTION_ITEMS_SUCCEEDED: 'FETCH_AUCTION_ITEMS_SUCCEEDED',
  FETCH_AUCTION_ITEMS_FAILURE: 'FETCH_AUCTION_ITEMS_FAILURE',
  CLEAR_SLOTS: 'CLEAR_SLOTS',

  // Bids
  FECTCH_LIVE_BIDDING_DETAILS_SUCCEEDED: 'FETCH_LIVE_BIDDING_DETAILS_SUCCEEDED',
  FETCH_BIDS_SUCCEEDED: 'FETCH_BIDS_SUCCEEDED',
  FETCH_BIDS_FAILURE: 'FETCH_BIDS_FAILURE'
};

export default ActionTypes;
