CREATE TABLE USERS (
  USER_ID SERIAL PRIMARY KEY,
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT,
  ROLE CHAR(20) NOT NULL,
  PASSWORD CHAR(50) NOT NULL,
  EMAIL CHAR(100) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL, 
  MODIFIED_AT TIMESTAMP NOT NULL
);

CREATE TABLE ITEMS (
  ITEM_ID SERIAL PRIMARY KEY,
  NAME CHAR(50) NOT NULL,
  DESCRIPTION TEXT,
  IMAGE_URL TEXT,
  MIN_BID_PRICE REAL NOT NULL,
  DATE_TIME TIMESTAMP NOT NULL,
  USERNAME TEXT NOT NULL,
  STATUS SMALLINT NOT NULL, -- 1: AUCTIONED, 2: POSTED
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

CREATE TABLE AUCTION (
  AUCTION_ID SERIAL PRIMARY KEY,
  ITEM_ID INT NOT NULL,
  START_TIME TIME NOT NULL,
  END_TIME TIME NOT NULL,
  BIDDING_DATE DATE NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

CREATE TABLE BIDS (
  USER_ID TEXT NOT NULL,
  AUCTION_ID INT NOT NULL,
  ITEM_ID INT NOT NULL,
  AMOUNT REAL NOT NULL,
  STATUS SMALLINT NOT NULL, --STATUS NUMBER (1:PENDING, 2:LOST, 3:WON)
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);
